print('==== DESAFIO 011 ====')
largura = float(input('Largura da parede: '))
altura = float(input('Altura da parede: '))
print('Sua parede tem área de {:.2f}m²'.format(largura * altura))
print('Para pintar essa parede você vai precisar de {}l de tinta'.format((largura * altura) / 2))
