print('==== DESAFIO 026 ====')
n = str(input('Digite uma frase: ')).strip().upper()
print(f'A letra A aparece {n.count("A")} vezes na frase.')
print(f'A primeira letra A apareceu na posição {n.find("A") + 1}')
print(f'A última letra A apareceu na posição {n.rfind("A") + 1}')